### ISSUE TITLE
- /pcap/conn.log missing from filebeat.modules connection entry

### ISSUE THREAD

**Issue by cyber-naut** [blacktop/docker-filebeat#2]
Hi, 

This is a request to add conn.log data from Zeek into this processing pipeline.

In the filebeat.yml file the `filebeat.modules` section for data type `connection` is missing the file path for the `conn.log` file generated by Zeek and it appears to not pass data on without it. Adding the below to the filebeat.yml config, rebuilding the docker image and deploying appears to add conn.log data. I've tested using the instructions on [blacktop/docker-zeek](https://github.com/blacktop/docker-zeek) and can now view conn.log data in Kibana.

```
  connection:
    enabled: true
    var.paths:
      - /pcap/conn*.log
```

https://github.com/blacktop/docker-filebeat/blob/fbe69aaa15df607907b866ab53d49ff74ee7ef95/config/filebeat.yml#L14

This repo and others are really useful, thanks!

**Comment by blacktop** [comment]
Thank you for letting me know 👍
